# Generated by Django 2.1 on 2018-08-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180831_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
    ]
