# Generated by Django 2.1 on 2018-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20180927_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amount',
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
