# Generated by Django 2.1.1 on 2018-10-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20181019_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupancy',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE')], default='SINGLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
    ]
