# Generated by Django 2.1.1 on 2018-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20181019_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type_name',
            field=models.CharField(default='Delux', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('A/C(Air Conditioned)', 'A/C(Air Conditioned)'), ('Non A/C(Non Air Conditioned)', 'Non A/C(Non Air Conditioned)')], default='Non A/C(Non Air Conditioned)', max_length=50),
        ),
    ]
