# Generated by Django 2.1.1 on 2018-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20181019_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Address'),
        ),
    ]
