# Generated by Django 2.1.1 on 2018-10-21 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181021_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=datetime.date(2018, 10, 21)),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='manager',
            name='birth_date',
            field=models.DateField(default=datetime.date(2018, 10, 21)),
        ),
        migrations.AddField(
            model_name='manager',
            name='contact',
            field=models.IntegerField(default=1234567890),
        ),
    ]
