# Generated by Django 2.1.1 on 2018-10-21 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181021_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='manager',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
