# Generated by Django 2.1.1 on 2018-10-21 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181021_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='contact',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=1234567890),
        ),
    ]
